# This is a basic workflow to help you get started with Actions

name: Docker Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:

  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: nelonoel/branch-name@v1
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        GITHUB_RUN_ID: ${{ github.run_id }} 
        
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker build
      run: |
        GITHUB_REPOSITORY_LC=$(echo "${GITHUB_REPOSITORY}" | tr [A-Z] [a-z])
        docker build -t ${GITHUB_REPOSITORY_LC}:${BRANCH_NAME}${{ env.GITHUB_RUN_ID }} --target=base .
    - name: docker push
      run: |
        GITHUB_REPOSITORY_LC=$(echo "${GITHUB_REPOSITORY}" | tr [A-Z] [a-z])
        docker push ${GITHUB_REPOSITORY_LC}:${BRANCH_NAME}${{ env.GITHUB_RUN_ID }}
    - name: docker run 
      run: |
       GITHUB_REPOSITORY_LC=$(echo "${GITHUB_REPOSITORY}" | tr [A-Z] [a-z])
       docker run --publish 8000:9376 --detach --name bb ${GITHUB_REPOSITORY_LC}:${BRANCH_NAME}${{ env.GITHUB_RUN_ID }} 'npm install --dev && npm run lint'
